// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/gateway.proto

package gateway

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Gateway service

func NewGatewayEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Gateway service

type GatewayService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (Gateway_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Gateway_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (Gateway_BidiStreamService, error)
}

type gatewayService struct {
	c    client.Client
	name string
}

func NewGatewayService(name string, c client.Client) GatewayService {
	return &gatewayService{
		c:    c,
		name: name,
	}
}

func (c *gatewayService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "Gateway.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayService) ClientStream(ctx context.Context, opts ...client.CallOption) (Gateway_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "Gateway.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &gatewayServiceClientStream{stream}, nil
}

type Gateway_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type gatewayServiceClientStream struct {
	stream client.Stream
}

func (x *gatewayServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *gatewayServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *gatewayServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *gatewayServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gatewayServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gatewayServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *gatewayService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Gateway_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "Gateway.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &gatewayServiceServerStream{stream}, nil
}

type Gateway_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type gatewayServiceServerStream struct {
	stream client.Stream
}

func (x *gatewayServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *gatewayServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *gatewayServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *gatewayServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gatewayServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gatewayServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gatewayService) BidiStream(ctx context.Context, opts ...client.CallOption) (Gateway_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "Gateway.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &gatewayServiceBidiStream{stream}, nil
}

type Gateway_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type gatewayServiceBidiStream struct {
	stream client.Stream
}

func (x *gatewayServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *gatewayServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *gatewayServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *gatewayServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gatewayServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gatewayServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *gatewayServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Gateway service

type GatewayHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, Gateway_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, Gateway_ServerStreamStream) error
	BidiStream(context.Context, Gateway_BidiStreamStream) error
}

func RegisterGatewayHandler(s server.Server, hdlr GatewayHandler, opts ...server.HandlerOption) error {
	type gateway interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type Gateway struct {
		gateway
	}
	h := &gatewayHandler{hdlr}
	return s.Handle(s.NewHandler(&Gateway{h}, opts...))
}

type gatewayHandler struct {
	GatewayHandler
}

func (h *gatewayHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.GatewayHandler.Call(ctx, in, out)
}

func (h *gatewayHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.GatewayHandler.ClientStream(ctx, &gatewayClientStreamStream{stream})
}

type Gateway_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type gatewayClientStreamStream struct {
	stream server.Stream
}

func (x *gatewayClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *gatewayClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *gatewayClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gatewayClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gatewayClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *gatewayHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.GatewayHandler.ServerStream(ctx, m, &gatewayServerStreamStream{stream})
}

type Gateway_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type gatewayServerStreamStream struct {
	stream server.Stream
}

func (x *gatewayServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *gatewayServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *gatewayServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gatewayServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gatewayServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *gatewayHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.GatewayHandler.BidiStream(ctx, &gatewayBidiStreamStream{stream})
}

type Gateway_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type gatewayBidiStreamStream struct {
	stream server.Stream
}

func (x *gatewayBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *gatewayBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *gatewayBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gatewayBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gatewayBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *gatewayBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
